package com.example.randommotivationword

class Map {
    public val motivationalPhrases = mapOf(
        1 to "Believe you can and you're halfway there.",
        2 to "The only way to do great work is to love what you do.",
        3 to "Success is not final, failure is not fatal: It is the courage to continue that counts.",
        4 to "The only person you are destined to become is the person you decide to be.",
        5 to "You are never too old to set another goal or to dream a new dream.",
        6 to "The future belongs to those who believe in the beauty of their dreams.",
        7 to "Don't watch the clock; do what it does. Keep going.",
        8 to "It does not matter how slowly you go as long as you do not stop.",
        9 to "The only limit to our realization of tomorrow will be our doubts of today.",
        10 to "You are capable of more than you know.",
        11 to "The harder you work for something, the greater you'll feel when you achieve it.",
        12 to "Success is walking from failure to failure with no loss of enthusiasm.",
        13 to "The secret of getting ahead is getting started.",
        14 to "The journey of a thousand miles begins with one step.",
        15 to "The only way to achieve the impossible is to it is possible.",
        16 to "Your time is limited, don't waste it living someone else's life.",
        17 to "Change your thoughts and you change your world.",
        18 to "You don’t have to be great to start, but you have to start to be great.",
        19 to "Remember that not getting what you want is sometimes a wonderful stroke of luck.",
        20 to "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
        21 to "The past cannot be changed. The future is yet in your power.",
        22 to "The only way to make sense out of change is to plunge into it, move with it, and join the dance.",
        23 to "Do not wait to strike till the iron is hot, but make it hot by striking.",
        24 to "You must be the change you wish to see in the world.",
        25 to "What you get by achieving your goals is not as important as what you become by achieving your goals.",
        26 to "You are the best!"
    )
    public val swearPhrases = mapOf(
        1 to "You're a waste of space.",
        2 to "I've seen smarter people while watching paint dry.",
        3 to "Your existence is an insult to humanity.",
        4 to "You're as useful as a screen door on a submarine.",
        5 to "You're not pretty enough to be this stupid.",
        6 to "Has anyone ever told you that you're a waste of oxygen?",
        7 to "You're the reason God created the middle finger.",
        8 to "You're about as useful as a knitted condom.",
        9 to "If brains were dynamite, you wouldn't have enough to blow your nose.",
        10 to "You're not the dumbest person in the world, but you better hope they don't die.",
        11 to "You're not yourself today. I noticed the improvement immediately.",
        12 to "You're a shining example of why the gene pool needs a lifeguard.",
        13 to "You're not the full quid, are you?",
        14 to "You're nothing but a sad, strange little man.",
        15 to "I'd agree with you, but then we'd both be wrong.",
        16 to "Your family tree must be a cactus because everyone on it is a prick.",
        17 to "You're not just a clown. You're the entire circus.",
        18 to "You're as bright as a black hole.",
        19 to "If ignorance is bliss, you must be the happiest person on this planet.",
        20 to "You're not the sharpest tool in the shed, are you?",
        21 to "You're like a hemorrhoid, a pain the a** that won't go away.",
        22 to "You're not the brightest crayon in the box.",
        23 to "You're like a Monday, nobody likes you.",
        24 to "You're as pleasant as a root canal.",
        25 to "You're a prime example of the limitations of human intelligence."
    )
}